---
title: "Cod diet: historical feeding ratios of cod"
author: "Max Lindmark & Michele Casini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
pdf_document: default
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.asp = 0.618,
  fig.align ='center'
)
```

# Intro
Fit gamma hurdle models to stomach content (non-negative, zeroes, continuous) data using `brms` with random ices rectangle as random factors + time period and other predictor variables

```{r lib, message=FALSE}
# Load libraries, install if needed
library(tidyverse); theme_set(theme_light(base_size = 10))
library(readxl)
library(tidylog)
library(RCurl)
library(viridis)
library(RColorBrewer)
library(patchwork)
library(brms)
library(tidybayes)

library(glmmTMB)
library(DHARMa)

# To load entire cache in interactive r session, do: qwraps2::lazyload_cache_dir(path = "R/analysis/cod_feeing_historical_cache/html")

# For parallel processing
options(mc.cores = parallel::detectCores()) 
```

## Define plot theme

```{r read coastline data, message=FALSE, warning=FALSE}
# Define plotting theme for main plot
theme_plot <- function(base_size = 10, base_family = "") {
  theme_light(base_size = 10, base_family = "") +
    theme(
      axis.text.x = element_text(angle = 90),
      axis.text = element_text(size = 8),
      legend.text = element_text(size = 8),
      legend.title = element_text(size = 8),
      legend.position = "bottom",
      legend.key.height = unit(0.2, "cm"),
      legend.margin = margin(0, 0, 0, 0),
      legend.box.margin = margin(-5, -5, -5, -5),
      strip.text = element_text(size = 8, colour = 'black', margin = margin()),
      strip.background = element_rect(fill = "grey90")
      )
}
```

## Read and plot data

```{r read and plot data}
d <- readr::read_csv("/Users/maxlindmark/Desktop/R_STUDIO_PROJECTS/cod_interactions/data/cod_diet_analysis.csv") %>% dplyr::select(-X1)

d <- d %>%
  mutate(ices_rect = as.factor(ices_rect),
         year = as.factor(year),
         time_period = as.factor(time_period),
         quarter = as.factor(quarter),
         depth2_sc = depth - mean(depth)) 

p1 <- ggplot(filter(d, quarter == 1), aes(time_period, FR_tot, color = time_period, fill = time_period)) + 
  ggdist::stat_halfeye(adjust = .5, width = 0.8, .width = 0, justification = -.1, point_colour = NA, alpha = 0.5) + 
  geom_point(shape = 21, color = "white", size = 1.3, alpha = .2, position = position_jitter(seed = 1, width = 0.1)) + 
  geom_boxplot(width = .15, outlier.shape = NA, fill = "white", alpha = 0.2) +  
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  guides(color = FALSE, fill = FALSE) +
  labs(x = "", y = "") +
  coord_flip(ylim = c(0, 0.2)) + # CROPPING FOR BETTER VIEW
  geom_text(data = d %>% filter(quarter == 1) %>% group_by(time_period, quarter) %>% summarise(n = n()),
            aes(y = 0.25, x = time_period, label = glue::glue("n = {n}")), nudge_x = 0.3) +
  theme(legend.position = "bottom") + 
  theme_classic(base_size = 10) +
  ggtitle("Quarter 1") +
  NULL

p2 <- ggplot(filter(d, quarter == 4), aes(time_period, FR_tot, color = time_period, fill = time_period)) + 
  ggdist::stat_halfeye(adjust = .5, width = 0.8, .width = 0, justification = -.1, point_colour = NA, alpha = 0.5) + 
  geom_point(shape = 21, color = "white", size = 1.3, alpha = .2, position = position_jitter(seed = 1, width = 0.1)) + 
  geom_boxplot(width = .15, outlier.shape = NA, fill = "white", alpha = 0.2) +  
  scale_color_brewer(palette = "Dark2") +
  scale_fill_brewer(palette = "Dark2") +
  guides(color = FALSE, fill = FALSE) +
  labs(x = "", y = "Feeding ratio") +
  coord_flip(ylim = c(0, 0.2)) + # CROPPING FOR BETTER VIEW
  geom_text(data = d %>% filter(quarter == 4) %>% group_by(time_period, quarter) %>% summarise(n = n()),
            aes(y = 0.25, x = time_period, label = glue::glue("n = {n}")), nudge_x = 0.3) +
  theme(legend.position = "bottom") + 
  theme_classic(base_size = 10) +
  ggtitle("Quarter 4") +
  NULL

p1 / p2
```

## Plot potential response variables... Unlike Haase, I want to work with individual stomachs

```{r plot potential response variables, cache=TRUE}
# First try a glmmTMB (for speed! Might switch to brms later)

# m_tweed <- glmmTMB(FR_tot ~ pred_weight_g + time_period + (1|time_period/year) + quarter + (1|ices_rect),
#               family = tweedie, data = d)
# 
# summary(m_tweed)
# 
# # Following this example: Post-model-fitting procedures with glmmTMB models - CRAN
# m_tweed_simres <- simulateResiduals(m_tweed)
# plot(m_tweed_simres)
# 
# # Now with gamma hurdle model
# m_zigamma <- glmmTMB(FR_tot ~ pred_weight_g + time_period + (1|time_period/year) + quarter + (1|ices_rect),
#                      zi = ~., family = ziGamma, data = d)
# 
# m_m_zigamma <- simulateResiduals(m_zigamma)
# plot(m_zigamma)



# Fit a brms model with rectangle as random factor? Year nested in time_period? Quarter?
# prior <-
#   prior(normal(500, 100), nlpar = "alphaW") +
#   prior(normal(500, 100), nlpar = "alphaC") +
#   prior(normal(-1.2, 0.3), nlpar = "thetaW") +
#   prior(normal(-1.2, 0.3), nlpar = "thetaC")

# Read about gamma hurdle models
# https://stats.stackexchange.com/questions/470464/interpreting-residual-plots-for-zero-inflated-linear-mixed-model?rq=1
# https://stats.stackexchange.com/questions/187824/how-to-model-non-negative-zero-inflated-continuous-data
# https://groups.google.com/g/brms-users/c/d5O73pcfaag
# https://discourse.mc-stan.org/t/need-help-understanding-hurdle-hurdle-gamma-models-using-brms/16736
# https://stats.stackexchange.com/questions/477803/need-help-understanding-hurdle-model-specification-and-results-interpretation
# https://seananderson.ca/2014/05/18/gamma-hurdle/
# https://discourse.mc-stan.org/t/estimates-in-hurdle-gamma-model/18934
# https://discourse.mc-stan.org/t/levels-within-levels/8814/4

# Problem that the "top" random effect has few levels?
# https://stats.stackexchange.com/questions/281159/minimum-number-of-repeated-measures-and-levels-per-nested-random-effect
# OK to have time period both as a fixed and in the random part?
# https://stats.stackexchange.com/questions/79360/mixed-effects-model-with-nesting
m1 <- brm(FR_tot ~ pred_weight_g + depth2_sc + time_period + (1|time_period/year) + quarter + (1|ices_rect),
          data = d, family = hurdle_gamma(link = "log", link_shape = "log", link_hu = "logit"),
          chains = 4, iter = 4000, cores = 4,
          control = list(adapt_delta = 0.95, max_treedepth = 15))

plot(m1)
conditional_effects(m1)
```




