---
title: "Cod & flounder diets: size based dissimiliarities"
author: "Max Lindmark & Michele Casini"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  df_print: paged
pdf_document: default
editor_options: 
  chunk_output_type: console
---
  
```{r setup, include = FALSE, cache=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 12,
  fig.asp = 0.618,
  fig.align ='center'
)
```

# Intro
Fit density (also referred to as CPUE) model with environmental predictors and use that to calculate weighted mean dissolved oxygen, temperature and depth of Baltic cod

```{r lib, message=FALSE}
# Load libraries, install if needed
library(tidyverse); theme_set(theme_classic(base_size = 10))
library(readxl)
library(tidylog)
library(RCurl)
library(viridis)
library(RColorBrewer)
library(patchwork)
library(janitor)
library(icesDatras)
library(mapdata)
library(patchwork)
library(rgdal)
library(raster)
library(sf)
library(rgeos)
library(chron)
library(lattice)
library(ncdf4)
library(marmap)
library(rnaturalearth)
library(rnaturalearthdata)
library(mapplots)
library(EnvStats)
library(qwraps2)
library(vegan)
library(cluster)
library(rphylopic)
library(png)
library(grid)
```

## For plots

```{r read coastline data, message=FALSE, warning=FALSE}
theme_clean <- function() {
  theme_minimal(base_family = "Barlow Semi Condensed") +
    theme(panel.grid.minor = element_blank(),
          plot.title = element_text(family = "BarlowSemiCondensed-Bold"),
          axis.title = element_text(family = "BarlowSemiCondensed-Medium"),
          strip.text = element_text(family = "BarlowSemiCondensed-Bold",
                                    size = rel(1), hjust = 0),
          strip.background = element_rect(fill = "grey80", color = NA))
}
```

## Read and plot data

```{r read and plot data}
# These data are for total and prey specific stomach models
# These data are for the diet analysis (all prey groups)
cod_prey <- readr::read_csv("/Users/maxlindmark/Desktop/R_STUDIO_PROJECTS/cod_interactions/data/pca_cod_diet_analysis.csv") %>% dplyr::select(-X1) %>% mutate(species = "COD") %>% filter(year > 2014) %>% filter(!quarter == 2) %>% droplevels()

fle_prey <- readr::read_csv("/Users/maxlindmark/Desktop/R_STUDIO_PROJECTS/cod_interactions/data/pca_fle_diet_analysis.csv") %>% dplyr::select(-X1) %>% mutate(species = "FLE") %>% filter(!quarter == 2) %>% droplevels()
```

## Prepare data for calculating Bray-Curtis dissimilarity index

```{r prep data and run examples}
# Following this: https://www.davidzeleny.net/anadat-r/doku.php/en:hier-agglom_examples
data(BCI)  # example using Baro Colorado data

BCI.log <- log1p(BCI) 

str(BCI.log)
BCI.log
head(BCI.log)
nrow(BCI.log)

bc.dist <- vegdist(BCI.log, method = 'bray')
bc.dist
print(bc.dist, diag = TRUE)

clust <- agnes(sqrt (bc.dist), method = 'ward') # calculate Ward's algorithm 
plot(clust, which.plot = 2)

# Now do diet data
head(BCI.log)
head(BCI.log)

head(data.frame(cod_prey))
str(cod_prey)
colnames(cod_prey)

hist(cod_prey$pred_cm)

# Prepare the cod data
cod_prey <- cod_prey %>% filter(pred_cm < 75)
cod_prey2 <- cod_prey %>% 
  mutate(size_class = paste(cut(pred_cm, breaks = c(seq(0, 100, 5))), "C", sep = "_")) %>% 
  dplyr::select(c(14:29, 31)) %>% 
  pivot_longer(1:16) %>% 
  group_by(size_class, name) %>% 
  summarise(mean_prey = mean(value)) %>% 
  pivot_wider(names_from = name, values_from = mean_prey) %>% 
  as.data.frame()
  
rownames(cod_prey2) <- factor(cod_prey2$size_class)
cod_prey2 <- cod_prey2 %>% dplyr::select(-size_class)
cod_prey2

# Prepare the flounder data
fle_prey2 <- fle_prey %>% 
  mutate(size_class = paste(cut(pred_cm, breaks = c(seq(0, 100, 5))), "F", sep = "_")) %>% 
  dplyr::select(c(14:29, 31)) %>% 
  pivot_longer(1:16) %>% 
  group_by(size_class, name) %>% 
  summarise(mean_prey = mean(value)) %>% 
  pivot_wider(names_from = name, values_from = mean_prey) %>% 
  as.data.frame()
  
rownames(fle_prey2) <- factor(fle_prey2$size_class)
fle_prey2 <- fle_prey2 %>% dplyr::select(-size_class)
fle_prey2

# Combine!
dd <- bind_rows(fle_prey2, cod_prey2)

# Plot!
dist <- vegdist(dd, method = 'bray')
print(dist, diag = TRUE)

clust <- agnes(sqrt(dist), method = 'ward') # calculate Ward's algorithm 
plot(clust, which.plot = 2)

groups <- cutree(clust, k = 5)
groups 

clust.hclust <- as.hclust(clust)
group.order <- groups[clust.hclust$order]
group.order
group.in.cluster <- unique (group.order)
group.in.cluster

plot(clust.hclust)
rect.hclust(clust.hclust, border = group.in.cluster, k = 5) 
legend ('topleft', legend = paste ('Cluster', 1:5), pch = 22, col = 1:5, bty = 'n')

NMDS <- metaMDS(vegdist(dd))  # note that I could use also "NMDS <- metaMDS (bc.dist)" here
# Ggplotting it... https://chrischizinski.github.io/rstats/vegan-ggplot2/
plot(NMDS, type = "t")
spec_size_scores <- as.data.frame(scores(NMDS))  #Using the scores function from vegan to extract the species scores and convert to a data.frame
spec_size_scores$Spec_size <- rownames(spec_size_scores)  # create a column of species, from the rownames of species.scores
head(spec_size_scores)  #look at the data

spec_size_scores <- spec_size_scores %>% 
  separate(Spec_size, c("Size_class", "Species"), sep = "_") %>% 
  separate(Size_class, c("Temp", "Size"), sep = c(",")) %>% 
  mutate(Species = ifelse(Species == "C", "Cod", "Flounder")) %>% 
  mutate(Size = gsub("\\[|\\]", "", Size)) %>% 
  mutate(Size = as.numeric(Size),
         Species = as.factor(Species))

# cod_sil <- "http://phylopic.org/assets/images/submissions/bba1800a-dd86-451d-a79b-c5944cfe5231.512.png"
# fle_sil <- "http://phylopic.org/assets/images/submissions/4c2220b9-68a8-4594-8dd8-229643e11c84.512.png"
# codlogo <- readPNG(getURLContent(cod_sil), native = T)
# flelogo <- readPNG(getURLContent(fle_sil), native = T)
# rphylopic::recolor_phylopic(codlogo, alpha = 0.2, color = "gray")
# codlogo2 <- rasterGrob(codlogo, interpolate = TRUE)
# flelogo2 <- rasterGrob(flelogo, interpolate = TRUE)

# https://jonlefcheck.net/2012/10/24/nmds-tutorial-in-r/

ggplot() + 
  geom_point(data = spec_size_scores, aes(x = NMDS1, y = NMDS2, color = Species, size = Size), alpha = 0.5) +  # add the species labels
  scale_size(range = c(0, 13), breaks = c(10, 20, 30, 40, 50, 60, 70)) +
  scale_color_brewer(palette = "Dark2") + 
  theme_light(base_size = 14) +
  coord_equal() +
  # annotation_custom(codlogo2, xmin = 0.1, xmax = 0.3, ymin = 0.1, ymax = 0.3) +
  # annotation_custom(flelogo2, xmin = -0.4, xmax = -0.2, ymin = -0.4, ymax = -0.2) +
  NULL

ggsave("figures/nmds_species_size.png", width = 6.5, height = 6.5, dpi = 600)

# https://jonlefcheck.net/2012/10/24/nmds-tutorial-in-r/
stressplot(NMDS)

```


